version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install cfn-lint
      - pip install taskcat

  build:
    commands:
      - cfn-lint cfn-main.yml
      - taskcat test run --config .taskcat.yml
